### ISSUE TITLE
Add Tor support, show to the user the onion address of the node to the user via qrcode

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/abcore#11]
Add Tor support such that the node can be reached from anywhere bypassing nat.

Make the onion address available to the user in both text as well as qrcode formats

you can then access your node from anywhere with your SPV mobile wallet for better security and privacy

**Comment by AlfaOmega33** [comment]
+1

**Comment by greenaddress** [comment]
implemented finally in 0.73 ! closing
