### ISSUE TITLE
QR code not fully visible on widescreen [ android TV/nexus player ]

### ISSUE THREAD

**Issue by gianlucamazza** [greenaddress/abcore#114]
ABCore is fully working and syncing on google nexus player.
There's a glitch showing the QR code in Dashboard: the qr code doesn't fully fit the screen on my widescreen TV.

![image](https://user-images.githubusercontent.com/25006045/82112711-c44fdc00-974f-11ea-9a73-7a393a7c59a3.png)

I'm running official Android 8 firmware.

**Comment by gianlucamazza** [comment]
the bug is also replicable using an android tv emulated device (AVD)
Type: Android TV (1080p)
Resolution is: 1920 x 1080

**Comment by caiofaustino** [comment]
The screen should be scrollable, do you have any navigation command on Android TV that does that?

**Comment by gianlucamazza** [comment]
confirmed, the scrollview/scrollbar is not visible but working with a remote
