### ISSUE TITLE
Playstore listing is gone

### ISSUE THREAD

**Issue by Giszmo** [greenaddress/abcore#116]
I noticed that abcore isn't available from Google Play anymore. https://play.google.com/store/apps/details?id=com.greenaddress.abcore yields "We're sorry, the requested URL was not found on this server."

**Comment by nilskp** [comment]
Seems to be back:
https://play.google.com/store/apps/details?id=com.greenaddress.abcore

**Comment by Giszmo** [comment]
Yes, issue is resolved since  a while.

**Comment by caiofaustino** [comment]
I'm curious, what is your use case for ABCore?

**Comment by nilskp** [comment]
> I'm curious, what is your use case for ABCore?

Not sure who you're asking, but I think the ability of being able to run a full node on a mobile device could vastly increase the number of full nodes, probably by an order of magnitude or more.

Most people are not going to run a server, but eventually, everyone's phone should be able to run a full node.

This means much better security for the individual user and also much better security for the network as a whole.

**Comment by caiofaustino** [comment]
Both of you really. Yeah I agree with that, but I seem to get a lot of skepticism about that idea because of battery, mobile data, processing power, storage. But I think those are manageable if done properly.

**Comment by Giszmo** [comment]
I only cared about its [reproducibility](https://walletscrutiny.com/android/com.greenaddress.abcore/) :D

That said I find it an interesting project but not for phones. Only for Androids that are wired by default like your fridge or so.
