### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by LittleHelp24** [greenaddress/abcore#28]
For two days now I cannot log in or send my money. I get no 2fa, now when I try loggin in it just says error. No reason why. I can log in with mobile but it never sends me my 2fa in order to withdrawal. Of course no suppose from their email "help". Is this a system error or what's going on with my wallet?

**Comment by greenaddress** [comment]
Hi, did you mean to submit this issue on a greenaddress wallet repository as opposed to bitcoin core for android?
