### ISSUE TITLE
Pruning support

### ISSUE THREAD

**Issue by sipa** [greenaddress/abcore#33]
I'm unable to set up abcore with pruning support. Even when adding it manually to bitcoin.conf, setup fails due to alleged lack of storage.

Ideally, there is a config option for pruning (set by default for 0.12!), and this is taken into account for disk space calculations.

**Comment by gabridome** [comment]
Yep. Same problem.

Il ven 13 mag 2016, 10:28 Pieter Wuille <notifications@github.com> ha
scritto:

**Comment by greenaddress** [comment]
I think it is already fixed now but f39b45d352b74c755b4d4196396795c2fd65a149 adds explicit prune support
