### ISSUE TITLE
ABCore randomly restarting

### ISSUE THREAD

**Issue by sipa** [greenaddress/abcore#34]
This is a problem I've been having for several releases, including the latest (0.48).

After stopping Core (by pressing the slider/button "Switch Core OFF"), and verifying that it indeed has stopped (debug.log shows "Shutdown: done"), the tray icon disappears. I leave the ABCore app, and remove it from the view of recently used apps (pressing the square button, and swiping the ABCore window off the screen).

Some time later (I think usually when leaving another, unrelated app), the ABCore tray icon automatically reappears, and it seems that it indeed is running again (by inspecting the debug.log). This makes it nearly unusable, as the memory/CPU/bandwidth usage is something I don't want to see appear unexpectedly.

The problem does not seem to occur if after stopping Core, and leaving ABCore, I go to the apps settings screen, and Force Kill the application.

I don't have the feature for automatically running when on power+wifi enabled.

**Comment by greenaddress** [comment]
fixed in 2cf694833ce1767659d95afbcd30cdda977eb37f

Sorry; it hit me and a friend as well (we run out of monthly mobile allowance), shouldn't happen anymore.

Mind you that the "power+wifi enabled." won't disable core if it was manually started when it was last started.

Will release after 0.13 final is out as 0.49

**Comment by greenaddress** [comment]
@sipa v0.49 is now available @ https://github.com/greenaddress/abcore/releases

Leaving this open in case there are more issues.

**Comment by sipa** [comment]
I haven't had the issue after upgrading. Thanks!
