### ISSUE TITLE
Use getblockchaininfo for progress estimation

### ISSUE THREAD

**Issue by sipa** [greenaddress/abcore#35]
Bitcoin Core has a built in progress estimator for verification progress, in the `getblockchaininfo` RPC, under key `verificationprogress`, which is based on estimated total transaction count rather than block height, and should be more accurate (but it's far from perfect either).

**Comment by greenaddress** [comment]
at last! fixed in v0.62! (see https://github.com/greenaddress/abcore/releases/tag/v0.62alphaPoC) - closing
