### ISSUE TITLE
Tor hidden service

### ISSUE THREAD

**Issue by ghost** [greenaddress/abcore#38]
Add an ability to run as a tor hidden service, please!

**Comment by greenaddress** [comment]
At the moment this requires manual enabling in Orbot Tor configuration but it is possible

**Comment by AlfaOmega33** [comment]
Very good, the request is related to this guide:

https://github.com/jonathancross/jc-docs/blob/master/Bitcoin_mobile_privacy.md

In order to make Android more and more independent of "external" services..

P.S: sorry for the retard!

**Comment by blackph1ll1p** [comment]
Please + I2P support!

**Comment by greenaddress** [comment]
added embbedded tor
