### ISSUE TITLE
Requesting BIP148 Binary support. 

### ISSUE THREAD

**Issue by shinobiusmonk** [greenaddress/abcore#40]
Well...enough said.

**Comment by greenaddress** [comment]
My understanding is that Luke-Jr Knots will have the support in the next release. Since ABCore supports Knots already should it just wait for the new release or use some other binaries as an additional options?

If additional, link to latest binaries and are they signed?

**Comment by lichtamberg** [comment]
www.uasf.co has binaries you can use (binaries have been uploaded to github and are linked correspondingly). There is also an instruction on how to compile them. Let me know if you need some more information. 

I would also like to invite you to the #UASF http://slack.bitcoincore.org/ channel - we would be really happy if you join and discuss with us?

**Comment by greenaddress** [comment]
https://github.com/greenaddress/abcore/releases/tag/v0.57alphaPoC

done, please open issues if you find problems with it

**Comment by lichtamberg** [comment]
I love you guys :D You rock!!!
