### ISSUE TITLE
Android Oreo, ABCore breaks (doesn't seem to start)

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/abcore#44]
Android Oreo, ABCore breaks (doesn't seem to start)

**Comment by greenaddress** [comment]
From a first look I don't think there's a native exception. Perhaps something to do with the rpc port not being accessible by default (some firewall?) - requires more investigation

**Comment by johngodden** [comment]
Confirmed, the 'start' button doesn't work. No errors, no way to troubleshoot. Bummer since Adam is telling people about ABCore. I was really excited to get it going on Android. Any resources to put toward getting this working and in a more stable situation?

**Comment by greenaddress** [comment]
@johngodden  fixed in v0.62, see release notes here https://github.com/greenaddress/abcore/releases/tag/v0.62alphaPoC - closing this issue

**Comment by johngodden** [comment]
Confirmed it's starting now, thanks!
