### ISSUE TITLE
Allow to ask for permission to use external storage

### ISSUE THREAD

**Issue by FelixWeis** [greenaddress/abcore#45]
Right now it's impossible to set the `datadir` to an external (or emulated) storage as the app doesn't ask for permissions.

https://developer.android.com/training/data-storage/files.html

**Comment by greenaddress** [comment]
Will have a look. Can you give some examples of locations? my device doesn't have SD card support but I guess emulated should allow me to test?

**Comment by greenaddress** [comment]
I'm not entirely sure, I think this should be fixed with v0.62, let me know if not, keeping open for now.

**Comment by AreYouLoco** [comment]
I am using version 0.70 on almost pure AOSP 7.1.2 and it asked me permission to the storage. So seems like fixed at least for me.
