### ISSUE TITLE
ABCore notification with dark theme broken

### ISSUE THREAD

**Issue by AreYouLoco** [greenaddress/abcore#61]
With the "Default Dark Theme" system-wide. There is dark text displayed on dark background for the ABCore notification.

Screenshot to be attached.

**Comment by greenaddress** [comment]
@AreYouLoco still planning to attach a screenshot?

**Comment by AreYouLoco** [comment]
Sorry for abandoning it. But the issue is solved somehow. I think it was related to Substratum more than ABCore. Thanks for reminding. Closing.
