### ISSUE TITLE
ZMQs disablled?

### ISSUE THREAD

**Issue by mandelmonkey** [greenaddress/abcore#87]
I had LND managing to connect using 0.17 but now with 0.18 I get 

```
unable to subscribe for zmq block events: dial tcp 127.0.0.1:28332: connect: connection refused
```

i'm wondering if ZMQs were disabled with the 0.18 releases?

**Comment by greenaddress** [comment]
No work in abcore has been done to disable zmq, not sure what the issue is, are you use zmq over tcp socker rather than over file socket is that correct?

**Comment by mandelmonkey** [comment]
I could connect now, not sure what the issue was but it is resolved now
